### ISSUE TITLE
ctz and clz for 0 gives unexpected result on older cpus

### ISSUE THREAD

**Issue by afinch7** [CraneStation/lightbeam#21]
Tests fail on older cpus(intel sandy bridge and older). `ctz` and `clz` give 0 instead of bit width. 
Cpus tested: `e5-2670 v1`(fail), `i7-3820`(fail), `i7-4790K`(pass)

I would assume this has to do with the way that `tzcnt` and `lzcnt` are implemented on these cpus.

**Comment by sunfishcode** [comment]
In theory, Cranelift [should already use the older bsr/bsr instructions in combination with a select](https://github.com/CraneStation/cranelift/blob/master/filetests/isa/x86/baseline_clz_ctz_popcount.clif) to handle the 0 case correctly. Can you say more about what target flags you're using, or if you're using cranelift-native to set the target?

**Comment by afinch7** [comment]
In this case I was just running tests via `cargo +nightly test`.

```
failures:

---- tests::op32::clz::as_param stdout ----
thread 'tests::op32::clz::as_param' panicked at '[quickcheck] TEST FAILED. Arguments: (0)', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.7.2/src/tester.rs:176:28
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- tests::op32::ctz::as_param stdout ----
thread 'tests::op32::ctz::as_param' panicked at '[quickcheck] TEST FAILED. Arguments: (0)', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.7.2/src/tester.rs:176:28

---- tests::op64::clz::as_param stdout ----
thread 'tests::op64::clz::as_param' panicked at '[quickcheck] TEST FAILED. Arguments: (0)', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.7.2/src/tester.rs:176:28

---- tests::op64::ctz::as_param stdout ----
thread 'tests::op64::ctz::as_param' panicked at '[quickcheck] TEST FAILED. Arguments: (0)', /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.7.2/src/tester.rs:176:28


failures:
    tests::op32::clz::as_param
    tests::op32::ctz::as_param
    tests::op64::clz::as_param
    tests::op64::ctz::as_param

test result: FAILED. 268 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by sunfishcode** [comment]
Oh, I somehow missed that this issue is in Lightbeam. So then the answer is yes, Lightbeam is currently using lzcnt and tzcnt [here](https://github.com/CraneStation/lightbeam/blob/master/src/backend.rs#L3233), and it'll need to do something different for older CPUs.
