### ISSUE TITLE
Milestone: Fibonacci function

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/lightbeam#3]
Recursive Fibonacci is a nice next milestone because it needs some control flow operators and calls, which should really help establish the shape of the backend.

The steps are:
 - Implement `if`+`else`+`end`.
     - We'll need a stack for tracking nested control flow constructs. To start with there's only one kind of control-flow stack entry, for if/else/end, but eventually we'll have more. It can hold [`DynamicLable`](https://docs.rs/dynasmrt/0.2.3/dynasmrt/struct.DynamicLabel.html)s to keep track of the labels for branching.
     - The result value of an `if` can be carried by the stack just like normal operator results. (For now; later with on-the-fly register allocation it can be more sophisticated.)
 - Implement calls
    - This is a good time to generalize the handling of function signatures. I think we can just collect all the `FuncType`s from the type section into a `Vec` and pass that around for now.
    - Optionally, to keep things simple for this step, we could limit support to just 6 integer arguments, to avoid having to deal with stack arguments just yet.

I've left out a lot of the low-level details here; feel free to ask for more detail!

**Comment by pepyakin** [comment]
I will work on that!

**Comment by Vurich** [comment]
For calls, is it acceptable to do a post-processing pass? It would still make runtime linear, although it would no longer be single-pass. I think for us that's acceptable, although I'd have to confirm that.

Also there's no need to limit ourselves to integer arguments, floats can just be passed in integer registers like they are on sysv x64 anyway AFAIK.
