### ISSUE TITLE
Side Quest: Integer arithmetic

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/lightbeam#4]
With #1 done, it's now straightforward to start work on the rest of the integer arithmetic opcodes as we can compile, execute, and test them. This can happen in the background, as #3 and the next few milestones won't depend on it. I'm filing it now to track it, and in case anyone else is interested in something to get started with.

I suggest doing the `i32` and `i64` versions of each instruction at the same time, because it's easy to do so on x86-64 :-). As always, feel free to ask questions!

-----

The simple cases first. `i32.add` is already done (aside, should we rename `add_i32` to `i32_add`?), so that's is an example to work from. Use `Rd` for 32-bit operations and `Rq` for 64-bit operations.

 - [x] add
 - [x] sub
 - [x] and
 - [x] or
 - [x] xor
 - [x] mul (for now, use the register-register form of `imul`)

Next, comparisons. x86 is a little weird here because `set<cc>` can only write to 8-bit registers. So I suggest using `xor REG, REG` to zero out the result register first, and then using `Rb(REG)` with `set<cc>` to write the result on top of it.

 - [x] eqz
 - [x] eq
 - [x] ne
 - [x] lt_s
 - [x] lt_u
 - [x] le_s
 - [x] le_u
 - [x] gt_s
 - [x] gt_u
 - [x] ge_s
 - [x] ge_u

Shift and rotates, they need their count operand in `%cl`, so we'll need a way to allocate that register specifically.

 - [x] shl
 - [x] shr_s
 - [x] shr_u
 - [x] rotl
 - [x] rotr

Div/rem. These also need specific registers, and they can also trap. I suggest starting with simple conditional branches testing the trap conditions and using `ud2` to do the traps for now.

 - [x] div_s
 - [x] div_u
 - [x] rem_s
 - [x] rem_u

These are easy if you have sufficiently new CPUs :-). At this step, we'll need to figure out how we want to handle subtarget features.

 - [x] clz
 - [x] ctz
 - [x] popcnt

**Comment by eira-fransham** [comment]
Inexplicably, `dynasm-rs` currently doesn't support `setb` and so it's not easily possible to support `i32.lt_u`. I have no good explanation for this, all the other condition codes are supported. You can see that it's missing from [the instruction reference](https://censoredusername.github.io/dynasm-rs/language/instructionref.html) and trying to use it causes the error `'setb' is not a valid instruction`.

**Comment by sunfishcode** [comment]
Just to keep things linked, the `setb` issue is reported at https://github.com/CensoredUsername/dynasm-rs/issues/38.

**Comment by Vurich** [comment]
So the only ones that are left are the trapping instructions, do you think it's a good idea to implement them by just letting them trap on error conditions since I'm going to implement wasmtime's trapping handlers as my next piece of work anyway?
