### ISSUE TITLE
Lightbeam vs Cranelift and Faerie

### ISSUE THREAD

**Issue by jlb6740** [CraneStation/lightbeam#6]
Having not used Cranelift but trying to undertsand around how all the projects in Cranestation fit and are to be used together, I have noticed that Cranelift has a component faerie that I think is intended to take Cranelift IR and create machine code. How does lightbeam compare? Is it intended to be a standalone tool or a component in a VM or something else?

**Comment by sunfishcode** [comment]
There's machine code, and then there's the .o container file format for machine code. Cranelift-codegen and LIghtbeam both produce machine code, with different tradeoffs in terms of how much compile time they take. Once we have machine machine code, there are two main things we can do with it:
 - Write it to a .o file, which can then be linked with other .o files and libraries to form native executables or libraries. We use the Faerie library to handle the .o file formats.
 - Write it into memory, and execute it from there, implementing a JIT. This doesn't use Faerie.

Also machine code doesn't operate in a vacuum, and must interoperate with other machine code. This is what Wasmtime helps with, providing conventions and runtime support for machine code implementing WebAssembly. This is needed whether the code is in .o files or in memor, so while Wasmtime uses cranelift-codegen in a JIT configuration right now, we also have some experiments using it in a .o file configuration with Faerie too.

Lightbeam is in an early stage of development right now, but as it matures, we expect to integrate it into Wasmtime as an alternate way to produce machine code.

**Comment by jlb6740** [comment]
Hi, thanks for the explanation. From what I read then, it sounds to me like cranelift-faerie produces machine code just like lightbeam intends plus it has support for creating proper object files linking and creating executables. If Faerie does all of this already then there seems to be overlap. Is lightbeam's calling to generate object code faster than cranelift-faerie? Is it ultimately intended to be the initial AOT or JIT compile for code that is later optimized and recompiled in wasmtime?

**Comment by sunfishcode** [comment]
Everything here with "faerie" in the name involves writing out .o container files. So cranelift-faerie is all about adapting code produced by cranelift and packaging it up using faerie to write a .o file.

Lightbeam does not currently have a faerie component and doesn't currently support writing out to .o container files. However, this is something we could plausibly add in the future. There may be some amount of overlap with cranelift-faerie, however most of the interesting logic is in the faerie library, which would be shared between the two.

Faerie does not perform linking of .o files. We currently depend on linkers from other toolchains to do that step.

Lightbeam is a single-pass compiler, so it takes very little time to compile, though it produces less efficient code, compared to Cranelift. Such a thing could be used as a first tier with Cranelift as a second tier, though I expect we'll ultimately support configurations with and without tiering.

**Comment by jlb6740** [comment]
Thanks for your response. So lightbeam is simply focused on being a fast single pass code generator, which is not necessarily the niche of cranelift-faerie. However, lightbeam is being designed with the idea of it potentially being useful as part of some tiered compilation potentially working with existing cranelift-faerie code ... hope that's right.

One more question, do either of these projects (lightbeam or cranelift-farie) have ambition to support any architecture other than x86-64 such as ARM ... or would that just be a nice to have?

**Comment by sunfishcode** [comment]
That's right. Lightbeam is focused on being a fast single-pass code generator, which is not necessarily the niche of cranelift-codegen (cranelift-faerie is the part that connects cranelift-codegen output to the faerie library for writing .o files).

And yes, both cranelift-codegen and lightbeam, as well as their faerie integration, intend to support other architectures in the future, including ARM.

**Comment by jlb6740** [comment]
Cool, Thanks!
